starhub/config/routes.rb
Rails.application.routes.draw do
  post 'messages/create'

  get 'messages/new'

  get 'messages/index'

  get 'home/index'

  devise_for :customers, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :products do
    resources :reviews
    resources :issues
  end
end

starhub/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

starhub/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :last_name, presence: true
  validates :username, uniqueness: true

  has_many :reviews
  has_many :issues
  has_many :reviewed_products, through: :reviews, source: :product
  has_many :problem_products, through: :issues, source: :product
end

starhub/app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :comment, length: { minimum: 20 }
  validates :status, inclusion: { in: %w(REPORTED INVESTIGATED FIX_IN_PROGRESS FIXED), message: "%{value} is not a valid status" }
  validates :severity, inclusion: { in: %w(COSMETIC MINOR MAJOR CRITICAL), message: "%{value} is not a valid severity level" }

end

starhub/app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews
  has_many :issues
  has_many :reviewing_customers, through: :reviews, source: :customer
  has_many :complaining_customers, through: :issues, source: :customer

  validates :name, length: { minimum: 6 }
  validates :code, length: { is: 4 }
  validates :category, inclusion: { in: %w(BOARD STRATEGY ARCADE RPG SHOOTER), message: "%{value} is not a valid category" }

  def average_ratings
    return 0 if reviews.empty?
    reviews.map { |r| r.rating }.inject(:+) / reviews.size
  end

  def issue_count
    list = issues.map { |issue| issue.severity }
    counts = Hash.new(0)
    list.each { |issue| counts[issue] += 1 }
    counts
  end
end

starhub/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :comment, length: { minimum: 10 }
  validates :rating, inclusion: { in: (1..5).to_a }

  def broadcast_save
    ActionCable.server.broadcast 'notification', status: 'created',
      id: id,
      product: self.product.name,
      reviewer: self.customer.username,
      rating: rating
  end
end

starhub/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

starhub/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_customer!, only: [:index, :new]

  def index
    @products = Product.all
  end

  def new
  end

  def edit
  end
end

starhub/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  API_HOST = 'http://localhost:3600'  

  def create
    @message = {content: params[:message][:content],
                originator: params[:message][:originator],
                recipient: params[:message][:recipient]}
    gateway = Messaging.new(API_HOST)
    gateway.send(@message) ?  flash.now[:notice] = 'Message sent!' :
      flash.now[:error] = 'Failed to send message!'

    render 'show', message: @message
  end

  def new
    @originator = Customer.find(params[:originator]).username
    @recipient = Customer.find(params[:recipient]).username
  end

  def index
    gateway = Messaging.new(API_HOST)
    @mailbox = Customer.find(params[:mailbox]).username
    @messages = gateway.receive(@mailbox, 1)
  end
end

starhub/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private
def sign_up_params
  params.require(:customer).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
end

def account_update_params
  params.require(:customer).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation, :current_password)
end

end

starhub/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = @product.reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = @product.reviews.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :show, status: :ok, location: @review }
    end
  end

  # GET /reviews/new
  def new
    @review = @product.reviews.build

    respond_to do |format|
      format.html
      format.json { render json: @review}
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = @product.reviews.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    create_params = review_params.merge({ customer_id: current_customer.id })
    @review = @product.reviews.create(create_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to [@review.product, @review], notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: [@review.product, @review] }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    @review = @product.reviews.find(params[:id])

    respond_to do |format|
      update_params = review_params.merge({ customer_id: current_customer.id })
      if @review.update_attributes(update_params)
        format.html { redirect_to [@review.product, @review], notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = @product.reviews.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to product_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:product_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

starhub/app/helpers/application_helper.rb
module ApplicationHelper
end

starhub/app/helpers/home_helper.rb
module HomeHelper

  def issue_ratings(count)
    return 0 if count.empty?
    return 5 if count['CRITICAL'] > 1
    return 4 if count['CRITICAL'] == 1
    return 3 if count['MAJOR'] > 1
    return 2 if count['MAJOR'] == 1
    return 1 if count['MINOR'] > 1
    return 1 if count['COSMETIC'] == 1 && count['MINOR'] == 1
    return 0
  end
end

starhub/app/helpers/messages_helper.rb
module MessagesHelper
end

starhub/app/helpers/reviews_helper.rb
module ReviewsHelper
end

starhub/app/views/home/index.html.erb
<h1>Starhub Products</h1>

<div class="half_line">
  <p class="to_left">
      Logged in as: <%= current_customer.username %>
      <span id="review_notification" class="to_right flash"></span>
  </p>
</div>

<br>
<br>

<table>
  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('odd_line', 'even_line') %>">

      <td>
        <%= image_tag("#{product.code}.jpg", alt: "#{product.name}", class: 'product_image') %>
      </td>
      <td class='product_description'>
        <dl>
          <dt><%= product.name %></dt>
          <dt><%= product.category%></dt>
        </dl>
      </td>
      <td>
        <table class='paddingColumns'>
          <tr>
            <th>Reviews</th>
            <th>Issues</th>
          </tr>
          <tr>
            <td>
              <% product.average_ratings.times do %>
                <%= image_tag('heart.png', alt: 'heart', class: 'rating_image') %>
              <% end %>
            </td>
            <td>
              <% issue_ratings(product.issue_count).times do %>
                <%= image_tag('warning.png', alt: 'warning', class: 'rating_image') %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>

            <%= link_to 'see all Reviews', product_reviews_path(product) %>
            </td>
            <td>
              <%= link_to 'See all Issues', product_issues_path(product) %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to 'Add a Review', new_product_review_path(product) %>

            </td>
            <td>
              <%= link_to 'Report an Issue',new_product_issue_path(product) %>
            </td>
          </tr>
        </table>
      </td>
      <td></td>
      <td class='product_actions'>
      <!-- we would enable these links only for admininstrators, not customers-->
        <%= link_to_if false, 'Edit', edit_product_path(product) %>
        <%= link_to_if false, 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- we would enable this link only for admininstrators, not customers-->
<%= link_to_if false, 'New Product', new_product_path, error: "Flash message" %>

<br>
<%= link_to "Log out", destroy_customer_session_path, method: :delete %>

starhub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starhub</title>
    <%= csrf_meta_tags %>

    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <%= yield %>
  </body>
</html>

starhub/app/views/messages/_form.html.erb
<%= form_tag "/messages/create" do %>
    <%= hidden_field_tag 'message[originator]', originator  %>
    <%= label_tag 'To:  ', nil, class: 'field' %>
    <%= text_field_tag 'message[recipient]', recipient %>
    <br>
    <br>
    <%= label_tag 'content', nil, class: 'field' %>
    <br>
    <%= text_area_tag 'message[content]', 'your message here', rows: 10, cols: 60 %>
    <br>
    <br>
    <%= submit_tag 'Send', class: 'actions' %>
    <br>
<% end %>

starhub/app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

starhub/app/views/messages/index.html.erb
<h1>Messages for <%= @mailbox %></h1>

<table>
  <thead>
    <tr>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>From</th>
      <th>Content</th>
    </tr>
    <% @messages.each do |msg| %>
      <tr>
        <td><%= msg['originator'] %></td>
        <td><%= msg['content'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', root_path %> 

starhub/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', originator: @originator, recipient: @recipient %>

<%= link_to 'Back', root_path %>

starhub/app/views/messages/show.html.erb
<p>
  <b>Recipient:</b>
  <%= @message.fetch(:recipient) %>
</p>

<p>
  <b>Content:</b>
  <%= @message.fetch(:content) %>
</p>

<%= link_to 'Back', root_path %> 

starhub/app/views/reviews/_form.html.erb
<%= form_for([@review.product, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :rating %>
    <%= f.select :rating, %w(1 2 3 4 5), prompt: '1 is worst, 5 is best' %>
  </div>
  <div class="field">
  <%= f.label :comment %><br>
  <%= f.text_area :comment, rows: 10, cols: 60 %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

starhub/app/views/reviews/edit.html.erb
<h1>Editing Review for <%= @product.name %></h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', [@review.product, @review] %> |
<%= link_to 'Back', product_reviews_path(@review.product) %>

starhub/app/views/reviews/index.html.erb
<h1>Reviews for <%= @product.name %></h1>
        <p>  <%= image_tag("#{@product.code}.jpg", alt: "#{@product.name}", class: 'product_image_index') %>   </p>

<table>
  <thead>
    <tr>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>Actions</th>
    </tr>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
          <td>
              <%= link_to 'Show', product_review_path(review.product, review) %>
          </td>
          <% if current_customer.id == review.customer.id%>
            <td>
                <%= link_to 'Edit', edit_product_review_path(review.product, review) %>
            </td>
            <td><%= link_to 'Destroy', [review.product, review], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_product_review_path %>
<span class='action_4'>
  <%= link_to 'Back to products', root_path %>
</span>

starhub/app/views/reviews/new.html.erb
<h1>New Review for <%= @product.name %></h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', product_reviews_path(@review.product) %>

starhub/app/views/reviews/show.html.erb
<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>


<span class="action_1">
  <%= link_to 'Back', product_reviews_path(@review.product) %>
</span>
<% if current_customer.id == @review.customer.id %>
  <span class="action_2">
    <%= link_to 'Edit', edit_product_review_path(@review.product, @review) %>
  </span>
  <% else %>
  <span class="action_3">
    <%= link_to(image_tag("mail.png"),
                    messages_new_path(params: {originator: current_customer,
                                              recipient: @review.customer}),
                    title: 'Send message to the reviewer',
                   data: { confirm: "You want to message the reviewer?" }) %>
  </span>
<% end %>

<span class="action_4">
  <%= link_to(image_tag("mailbox.png"),
                  messages_index_path(params: {mailbox: current_customer}),
                  title: 'Read new messages',
                 data: { confirm: "You want to read new messages?" }) %>
</span>